# Generated by Django 5.0.4 on 2024-05-08 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://www.miagrillandbar.com/wp-content/uploads/2020/04/dish-image-no.jpg', max_length=500),
        ),
    ]
